add inherit class Student in person and testing
SecurityLab-UCD/python-io-capture pull request #2
Opened 2023-07-06 05:32 UTC by harrison4anewbe

Add inherit class Student in person.py and testing in driver.py

2023-07-07 03:26 UTC, EYH0602 approved these changes

2023-07-07 03:26 UTC, EYH0602 commented on example_project/person.py
> +class Student(Person):
Adding an overload constructor `__init__` with an additional parameter might be useful. Call `Person.__init__` inside it and see what happens.

For example,

```py
class Student(Person):
    def __init__(self, name, age, sid):
        Person.__init__(self, name, age)
        self.id = sid
```

2023-07-09 02:25 UTC, DataCorrupted requested changes

2023-07-09 02:25 UTC, DataCorrupted commented on src/driver.py
> +    student1.introduce()
Can you add:

```py
# Also import typing
person_list: List[Person] = [person1, student1]
```
Then use that list for something.
Say a for loop and everyone `introduce` themselves.

2023-07-10 22:22 UTC, DataCorrupted approved these changes

2023-07-17 18:40 UTC, DataCorrupted approved these changes

2023-07-18 01:34 UTC, farhad-alemi approved these changes

2023-07-19 00:06 UTC, merged